const c=document.getElementById('content'), title=document.getElementById('title'), modal=document.getElementById('sosModal');const tabs=[...document.querySelectorAll('nav [data-tab]')];let score=Number(localStorage.tapScore||0),confirmCount=0,taps=[];
const card=x=>`<section class="card">${x}</section>`;
const chats=[['👩','Mama','Kannst du nachher noch Brot mitbringen?','12:41','2'],['👨','Papa','👍 Alles klar, bis später','11:58',''],['👧','Lisa','Foto','10:22','1'],['👦','Noah','Ich bin gleich zuhause','Gestern',''],['👨‍👩‍👧‍👦','Familie','Mama: Sonntag um 14 Uhr?','Gestern','4']];
const pages={chat:()=>`<div class="search">🔎 Suchen</div>${chats.map(x=>`<div class="chatrow"><div class="avatar">${x[0]}</div><div class="chatbody"><div class="line"><span class="name">${x[1]}</span><span class="time">${x[3]}</span></div><div class="line"><span class="preview">${x[2]}</span>${x[4]?`<span class="badge">${x[4]}</span>`:''}</div></div></div>`).join('')}`,
feed:()=>card(`<div class="posthead"><div class="avatar">👩</div><div><b>Mama</b><div class="muted">Heute, 14:05</div></div></div><div class="photo">👨‍👩‍👧‍👦</div><p>Sonntag zusammen ❤️</p>`)+card(`<div class="posthead"><div class="avatar">👨</div><div><b>Papa</b><div class="muted">Heute, 12:22</div></div></div><p>Wer ist heute Abend bei Pizza dabei? 🍕</p>`),
games:()=>card(`<h2>🎮 Spiele</h2><div class="event"><span><b>Block Blast!</b><br><span class="muted">Externes Spiel · Demo</span></span><button class="primary" id="external">Spiel öffnen</button></div><div class="score"><span>🥇 Lisa</span><b>48.250</b></div><div class="score"><span>🥈 Papa</span><b>37.190</b></div><div class="score"><span>🥉 Mama</span><b>29.820</b></div><p class="muted">Highscores werden in dieser Demo nicht aus Block Blast ausgelesen.</p>`)+card(`<h2>Family Tap Challenge</h2><p>Dein Score: <b id="score">${score}</b></p><button class="gamebtn" id="tap">TIPP!</button>`),
calendar:()=>card(`<h2>📅 Familienkalender</h2><button class="primary">+ Eintrag</button><div class="event"><span>🏖 Urlaub Papa <span class="pill">Mama · Lisa</span></span><span>12.–26. Aug</span></div><div class="event"><span>🎂 Oma Geburtstag <span class="pill">Alle</span></span><span>Morgen</span></div><div class="event"><span>⚽ Fußball Noah <span class="pill">Familie</span></span><span>Mo 17:00</span></div><p class="muted">Bei einer echten Anmeldung wird der eingetragene Geburtstag automatisch jährlich übernommen.</p>`),
map:()=>card(`<h2>📍 Standort teilen</h2><p>Bestimme, wer deinen Live-Standort sehen darf.</p><div class="check"><span>👩 Mama</span><input type="checkbox" checked></div><div class="check"><span>👨 Papa</span><input type="checkbox" checked></div><div class="check"><span>👧 Lisa</span><input type="checkbox"></div><div class="setting"><span>Dauer</span><b>1 Stunde ›</b></div><button class="primary">Standortfreigabe starten</button>`)+card(`<h3>Familienkarte · Demo</h3><div class="map"><span class="marker a">👩</span><span class="marker b">👨</span><span class="marker c">👧</span></div>`),
settings:()=>card(`<h2>⚙️ Einstellungen</h2><div class="setting"><span>👤 Profil & Geburtstag</span><span>›</span></div><div class="setting"><span>🚨 SOS-Empfänger</span><span>Mama, Papa ›</span></div><div class="setting"><span>📍 Standortberechtigungen</span><span>›</span></div><div class="setting"><span>🔔 Benachrichtigungen</span><span>›</span></div>`)+card(`<div class="notice"><b>Demo-Modus:</b> Es werden keine echten SOS-Nachrichten, Push-Mitteilungen oder Standortdaten an andere Personen gesendet.</div>`)};
const names={chat:'Chats',feed:'Familien-Feed',games:'Spiele',calendar:'Kalender',map:'Standort',settings:'Mehr'};
function show(tab){tabs.forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));title.textContent=names[tab];c.innerHTML=pages[tab]();if(tab==='games'){document.getElementById('tap').onclick=()=>{score++;localStorage.tapScore=score;document.getElementById('score').textContent=score};document.getElementById('external').onclick=()=>alert('Demo: Hier würde später das externe Spiel offiziell geöffnet werden.')}}
function openSOS(){modal.classList.remove('hidden');modal.innerHTML=`<div class="dialog"><h2>🚨 SOS</h2><p>Wollen Sie wirklich einen Alarm auslösen?</p><div class="progress">Bestätigung: ${confirmCount} von 8</div><p class="muted">8× „Ja“ oder 8 schnelle Taps auf den roten SOS-Knopf lösen den Demo-Alarm aus.</p><div class="actions"><button class="no">Nein</button><button class="yes">Ja</button></div></div>`;modal.querySelector('.no').onclick=()=>{confirmCount=0;modal.classList.add('hidden')};modal.querySelector('.yes').onclick=()=>{confirmCount++;confirmCount>=8?alarm():openSOS()}}
function alarm(){confirmCount=0;modal.classList.remove('hidden');modal.innerHTML=`<div class="dialog alarm"><h2>🚨 NOTFALL AUSGELÖST · DEMO</h2><p><b>👤 Güner</b><br><span class="muted">Gerade eben</span></p><div class="alarmmap">📍</div><div class="event"><span>Jetzt</span><b>Aktueller Standort</b></div><div class="event"><span>vor 5 Min</span><span>Letzte Position</span></div><div class="event"><span>vor 10 Min</span><span>Letzte Position</span></div><div class="event"><span>vor 20 Min</span><span>Letzte Position</span></div><div class="event"><span>vor 1 Std</span><span>Letzte Position</span></div><p class="notice">Testmodus: Es wurde niemand benachrichtigt und kein Standort übertragen.</p><button class="primary" id="closeAlarm">Demo schließen</button></div>`;document.getElementById('closeAlarm').onclick=()=>modal.classList.add('hidden')}
document.getElementById('sosNav').onclick=()=>{let now=Date.now();taps=taps.filter(t=>now-t<4000);taps.push(now);if(taps.length>=8){taps=[];alarm()}else openSOS()};tabs.forEach(b=>b.onclick=()=>show(b.dataset.tab));if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');show('chat');
